#server:
#  port: 8082
#spring:
#  application:
#    name: consumer
#
#eureka:
#  instance:
#    hostname: 127.0.0.1
#  client:
#    registerWithEureka: true
#    fetchRegistry: true
#    serviceUrl:
#      defaultZone: http://localhost:1112/eureka/,http://localhost:1111/eureka/
spring:
  application:
    name: ribbon-consumer2
server:
  port: 9000

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:1111/eureka/