spring:
  application:
    name: fegin-consumer
server:
  port: 9001

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:1111/eureka/
